openapi: 3.0.3

info:
  title: API Logistica
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: Autenticación

  - name: Usuarios

  - name: Paquetes

  - name: Centros de Distribucion

  - name: Unidades

paths:

  /api/auth/login:
    $ref: './endpoints/login.yml'

  /api/auth/roles:
    $ref: './endpoints/roles.yml'

  /api/usuarios:
    $ref: './endpoints/usuarios.yml'

  /api/usuarios/{id}:
    $ref: './endpoints/usuario.yml'

  /api/paquetes:
    $ref: './endpoints/paquetes.yml'

  /api/paquetes/{folio}:
    $ref: './endpoints/paquete.yml'

  /api/centros-distribucion:
    $ref: './endpoints/centros-distribucion.yml'

  /api/centros-distribucion/{id}:
    $ref: './endpoints/centro-distribucion.yml'

  /api/unidades:
    $ref: './endpoints/unidades.yml'

  /api/unidades/{id}:
    $ref: './endpoints/unidad.yml'