openapi: 3.0.3

info:
  title: API Logistica
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: Autenticación

  - name: Usuarios

paths:

  /api/auth/login:
    $ref: './endpoints/login.yml'

  /api/usuarios:
    $ref: './endpoints/usuarios.yml'

  /api/usuarios/{id}:
    $ref: './endpoints/usuario.yml'